/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        'primary': '#667eea',
        'primary-light': '#8b9df0',
        'primary-dark': '#4c63d2',
        'secondary': '#764ba2',
        'secondary-light': '#9b7bc7',
        'secondary-dark': '#5a3a7d',
        'accent': '#f093fb',
        'accent-light': '#f5b3fc',
        'accent-dark': '#e873f8',
        'success': '#36d399',
        'success-light': '#6ee7b7',
        'success-dark': '#10b981',
        'warning': '#fbbd23',
        'warning-light': '#fcd34d',
        'warning-dark': '#f59e0b',
        'error': '#f87272',
        'error-light': '#fca5a5',
        'error-dark': '#ef4444',
        'info': '#3abff8',
        'info-light': '#7dd3fc',
        'info-dark': '#0ea5e9',
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        dijinvoice: {
          "primary": "#667eea",
          "secondary": "#764ba2", 
          "accent": "#f093fb",
          "neutral": "#2a2e37",
          "base-100": "#ffffff",
          "info": "#3abff8",
          "success": "#36d399",
          "warning": "#fbbd23",
          "error": "#f87272",
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
}