// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCompany(arg1) {
  return window['go']['main']['App']['CreateCompany'](arg1);
}

export function CreateCustomer(arg1) {
  return window['go']['main']['App']['CreateCustomer'](arg1);
}

export function CreateInvoice(arg1) {
  return window['go']['main']['App']['CreateInvoice'](arg1);
}

export function CreatePayment(arg1) {
  return window['go']['main']['App']['CreatePayment'](arg1);
}

export function CreatePaymentType(arg1) {
  return window['go']['main']['App']['CreatePaymentType'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['main']['App']['CreateProduct'](arg1);
}

export function CreateProductCategory(arg1) {
  return window['go']['main']['App']['CreateProductCategory'](arg1);
}

export function CreatePurchaseInvoice(arg1) {
  return window['go']['main']['App']['CreatePurchaseInvoice'](arg1);
}

export function CreatePurchaseProduct(arg1) {
  return window['go']['main']['App']['CreatePurchaseProduct'](arg1);
}

export function CreatePurchaseProductCategory(arg1) {
  return window['go']['main']['App']['CreatePurchaseProductCategory'](arg1);
}

export function CreateSalesCategory(arg1) {
  return window['go']['main']['App']['CreateSalesCategory'](arg1);
}

export function CreateSalesInvoice(arg1) {
  return window['go']['main']['App']['CreateSalesInvoice'](arg1);
}

export function CreateSampleData() {
  return window['go']['main']['App']['CreateSampleData']();
}

export function CreateSupplier(arg1) {
  return window['go']['main']['App']['CreateSupplier'](arg1);
}

export function CreateTaxRate(arg1) {
  return window['go']['main']['App']['CreateTaxRate'](arg1);
}

export function CreateUnitOfMeasurement(arg1) {
  return window['go']['main']['App']['CreateUnitOfMeasurement'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['main']['App']['DeleteCustomer'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeletePayment(arg1) {
  return window['go']['main']['App']['DeletePayment'](arg1);
}

export function DeletePaymentType(arg1) {
  return window['go']['main']['App']['DeletePaymentType'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function DeletePurchaseInvoice(arg1) {
  return window['go']['main']['App']['DeletePurchaseInvoice'](arg1);
}

export function DeletePurchaseProduct(arg1) {
  return window['go']['main']['App']['DeletePurchaseProduct'](arg1);
}

export function DeletePurchaseProductCategory(arg1) {
  return window['go']['main']['App']['DeletePurchaseProductCategory'](arg1);
}

export function DeleteSalesCategory(arg1) {
  return window['go']['main']['App']['DeleteSalesCategory'](arg1);
}

export function DeleteSalesInvoice(arg1) {
  return window['go']['main']['App']['DeleteSalesInvoice'](arg1);
}

export function DeleteSupplier(arg1) {
  return window['go']['main']['App']['DeleteSupplier'](arg1);
}

export function DeleteTaxRate(arg1) {
  return window['go']['main']['App']['DeleteTaxRate'](arg1);
}

export function DeleteUnitOfMeasurement(arg1) {
  return window['go']['main']['App']['DeleteUnitOfMeasurement'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DownloadInvoicePDF(arg1) {
  return window['go']['main']['App']['DownloadInvoicePDF'](arg1);
}

export function GenerateInvoiceHTML(arg1) {
  return window['go']['main']['App']['GenerateInvoiceHTML'](arg1);
}

export function GenerateInvoiceHTMLArabic(arg1) {
  return window['go']['main']['App']['GenerateInvoiceHTMLArabic'](arg1);
}

export function GenerateInvoiceHTMLBilingual(arg1) {
  return window['go']['main']['App']['GenerateInvoiceHTMLBilingual'](arg1);
}

export function GenerateInvoiceHTMLEnglish(arg1) {
  return window['go']['main']['App']['GenerateInvoiceHTMLEnglish'](arg1);
}

export function GenerateInvoicePDF(arg1) {
  return window['go']['main']['App']['GenerateInvoicePDF'](arg1);
}

export function GenerateSampleQRCode() {
  return window['go']['main']['App']['GenerateSampleQRCode']();
}

export function GetAuthContext() {
  return window['go']['main']['App']['GetAuthContext']();
}

export function GetCompanies() {
  return window['go']['main']['App']['GetCompanies']();
}

export function GetCompany() {
  return window['go']['main']['App']['GetCompany']();
}

export function GetCompanyByID(arg1) {
  return window['go']['main']['App']['GetCompanyByID'](arg1);
}

export function GetCompanyLogoAsBase64(arg1) {
  return window['go']['main']['App']['GetCompanyLogoAsBase64'](arg1);
}

export function GetCompressionSettings() {
  return window['go']['main']['App']['GetCompressionSettings']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetCustomerByID(arg1) {
  return window['go']['main']['App']['GetCustomerByID'](arg1);
}

export function GetCustomers() {
  return window['go']['main']['App']['GetCustomers']();
}

export function GetDefaultProductSettings() {
  return window['go']['main']['App']['GetDefaultProductSettings']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetFilesByEntity(arg1, arg2) {
  return window['go']['main']['App']['GetFilesByEntity'](arg1, arg2);
}

export function GetInvoiceByID(arg1) {
  return window['go']['main']['App']['GetInvoiceByID'](arg1);
}

export function GetInvoices() {
  return window['go']['main']['App']['GetInvoices']();
}

export function GetOpenSalesInvoices() {
  return window['go']['main']['App']['GetOpenSalesInvoices']();
}

export function GetPaymentByID(arg1) {
  return window['go']['main']['App']['GetPaymentByID'](arg1);
}

export function GetPaymentTypes() {
  return window['go']['main']['App']['GetPaymentTypes']();
}

export function GetPayments() {
  return window['go']['main']['App']['GetPayments']();
}

export function GetPaymentsByInvoiceID(arg1) {
  return window['go']['main']['App']['GetPaymentsByInvoiceID'](arg1);
}

export function GetProductCategories() {
  return window['go']['main']['App']['GetProductCategories']();
}

export function GetProducts() {
  return window['go']['main']['App']['GetProducts']();
}

export function GetPurchaseInvoiceByID(arg1) {
  return window['go']['main']['App']['GetPurchaseInvoiceByID'](arg1);
}

export function GetPurchaseInvoices() {
  return window['go']['main']['App']['GetPurchaseInvoices']();
}

export function GetPurchaseProductCategories() {
  return window['go']['main']['App']['GetPurchaseProductCategories']();
}

export function GetPurchaseProducts() {
  return window['go']['main']['App']['GetPurchaseProducts']();
}

export function GetQRCodeInfo(arg1) {
  return window['go']['main']['App']['GetQRCodeInfo'](arg1);
}

export function GetSalesCategories() {
  return window['go']['main']['App']['GetSalesCategories']();
}

export function GetSalesInvoiceByID(arg1) {
  return window['go']['main']['App']['GetSalesInvoiceByID'](arg1);
}

export function GetSalesInvoices() {
  return window['go']['main']['App']['GetSalesInvoices']();
}

export function GetSupplierByID(arg1) {
  return window['go']['main']['App']['GetSupplierByID'](arg1);
}

export function GetSuppliers() {
  return window['go']['main']['App']['GetSuppliers']();
}

export function GetSystemSettings() {
  return window['go']['main']['App']['GetSystemSettings']();
}

export function GetTaxRates() {
  return window['go']['main']['App']['GetTaxRates']();
}

export function GetTodaysSales() {
  return window['go']['main']['App']['GetTodaysSales']();
}

export function GetTopSellingProducts() {
  return window['go']['main']['App']['GetTopSellingProducts']();
}

export function GetUnitsOfMeasurement() {
  return window['go']['main']['App']['GetUnitsOfMeasurement']();
}

export function GetUsersByCompany(arg1) {
  return window['go']['main']['App']['GetUsersByCompany'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MarkIntroAsViewed(arg1) {
  return window['go']['main']['App']['MarkIntroAsViewed'](arg1);
}

export function MarkPurchaseInvoiceReceived(arg1) {
  return window['go']['main']['App']['MarkPurchaseInvoiceReceived'](arg1);
}

export function OpenPDFInViewer(arg1) {
  return window['go']['main']['App']['OpenPDFInViewer'](arg1);
}

export function PopulateSampleData() {
  return window['go']['main']['App']['PopulateSampleData']();
}

export function PrintInvoiceHTML(arg1) {
  return window['go']['main']['App']['PrintInvoiceHTML'](arg1);
}

export function ResetIntroStatus(arg1) {
  return window['go']['main']['App']['ResetIntroStatus'](arg1);
}

export function SaveInvoiceHTML(arg1) {
  return window['go']['main']['App']['SaveInvoiceHTML'](arg1);
}

export function SaveInvoiceHTMLArabic(arg1) {
  return window['go']['main']['App']['SaveInvoiceHTMLArabic'](arg1);
}

export function SaveInvoiceHTMLBilingual(arg1) {
  return window['go']['main']['App']['SaveInvoiceHTMLBilingual'](arg1);
}

export function SaveInvoiceHTMLEnglish(arg1) {
  return window['go']['main']['App']['SaveInvoiceHTMLEnglish'](arg1);
}

export function ShowError(arg1, arg2) {
  return window['go']['main']['App']['ShowError'](arg1, arg2);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function ShowSaveDialog(arg1) {
  return window['go']['main']['App']['ShowSaveDialog'](arg1);
}

export function Signup(arg1) {
  return window['go']['main']['App']['Signup'](arg1);
}

export function SwitchCompany(arg1) {
  return window['go']['main']['App']['SwitchCompany'](arg1);
}

export function TestCustomerNAHandling() {
  return window['go']['main']['App']['TestCustomerNAHandling']();
}

export function UpdateCompany(arg1) {
  return window['go']['main']['App']['UpdateCompany'](arg1);
}

export function UpdateCompressionSettings(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateCompressionSettings'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateCustomer(arg1) {
  return window['go']['main']['App']['UpdateCustomer'](arg1);
}

export function UpdateDefaultProductSettings(arg1) {
  return window['go']['main']['App']['UpdateDefaultProductSettings'](arg1);
}

export function UpdateLastBackupTime(arg1) {
  return window['go']['main']['App']['UpdateLastBackupTime'](arg1);
}

export function UpdatePayment(arg1) {
  return window['go']['main']['App']['UpdatePayment'](arg1);
}

export function UpdatePaymentType(arg1) {
  return window['go']['main']['App']['UpdatePaymentType'](arg1);
}

export function UpdateProduct(arg1) {
  return window['go']['main']['App']['UpdateProduct'](arg1);
}

export function UpdatePurchaseInvoice(arg1) {
  return window['go']['main']['App']['UpdatePurchaseInvoice'](arg1);
}

export function UpdatePurchaseProduct(arg1) {
  return window['go']['main']['App']['UpdatePurchaseProduct'](arg1);
}

export function UpdatePurchaseProductCategory(arg1) {
  return window['go']['main']['App']['UpdatePurchaseProductCategory'](arg1);
}

export function UpdateSalesCategory(arg1) {
  return window['go']['main']['App']['UpdateSalesCategory'](arg1);
}

export function UpdateSalesInvoice(arg1) {
  return window['go']['main']['App']['UpdateSalesInvoice'](arg1);
}

export function UpdateSupplier(arg1) {
  return window['go']['main']['App']['UpdateSupplier'](arg1);
}

export function UpdateSystemSettings(arg1) {
  return window['go']['main']['App']['UpdateSystemSettings'](arg1);
}

export function UpdateTaxRate(arg1) {
  return window['go']['main']['App']['UpdateTaxRate'](arg1);
}

export function UpdateUnitOfMeasurement(arg1) {
  return window['go']['main']['App']['UpdateUnitOfMeasurement'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['main']['App']['UpdateUser'](arg1);
}

export function UploadCompanyLogo() {
  return window['go']['main']['App']['UploadCompanyLogo']();
}

export function UploadCompanyLogoFromData(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadCompanyLogoFromData'](arg1, arg2, arg3);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function ValidateZATCAQRCode(arg1) {
  return window['go']['main']['App']['ValidateZATCAQRCode'](arg1);
}

export function ViewInvoiceHTML(arg1) {
  return window['go']['main']['App']['ViewInvoiceHTML'](arg1);
}

export function ViewInvoiceHTMLArabic(arg1) {
  return window['go']['main']['App']['ViewInvoiceHTMLArabic'](arg1);
}

export function ViewInvoiceHTMLBilingual(arg1) {
  return window['go']['main']['App']['ViewInvoiceHTMLBilingual'](arg1);
}

export function ViewInvoiceHTMLEnglish(arg1) {
  return window['go']['main']['App']['ViewInvoiceHTMLEnglish'](arg1);
}

export function ViewInvoicePDF(arg1) {
  return window['go']['main']['App']['ViewInvoicePDF'](arg1);
}
