// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function CreateCustomer(arg1:database.Customer):Promise<void>;

export function CreateInvoice(arg1:database.Invoice):Promise<void>;

export function CreatePayment(arg1:database.Payment):Promise<void>;

export function CreatePaymentType(arg1:database.PaymentType):Promise<void>;

export function CreateProduct(arg1:database.Product):Promise<void>;

export function CreateProductCategory(arg1:database.ProductCategory):Promise<void>;

export function CreateSalesCategory(arg1:database.SalesCategory):Promise<void>;

export function CreateTaxRate(arg1:database.TaxRate):Promise<void>;

export function CreateUnitOfMeasurement(arg1:database.UnitOfMeasurement):Promise<void>;

export function DeleteCustomer(arg1:number):Promise<void>;

export function DeletePayment(arg1:number):Promise<void>;

export function DeletePaymentType(arg1:number):Promise<void>;

export function DeleteSalesCategory(arg1:number):Promise<void>;

export function DeleteTaxRate(arg1:number):Promise<void>;

export function DeleteUnitOfMeasurement(arg1:number):Promise<void>;

export function GenerateInvoicePDF(arg1:number):Promise<string>;

export function GenerateSampleQRCode():Promise<string>;

export function GetCompany():Promise<database.Company>;

export function GetCustomerByID(arg1:number):Promise<database.Customer>;

export function GetCustomers():Promise<Array<database.Customer>>;

export function GetDefaultProductSettings():Promise<database.DefaultProductSettings>;

export function GetInvoiceByID(arg1:number):Promise<database.Invoice>;

export function GetInvoices():Promise<Array<database.Invoice>>;

export function GetPaymentByID(arg1:number):Promise<database.Payment>;

export function GetPaymentTypes():Promise<Array<database.PaymentType>>;

export function GetPayments():Promise<Array<database.Payment>>;

export function GetPaymentsByInvoiceID(arg1:number):Promise<Array<database.Payment>>;

export function GetProductCategories():Promise<Array<database.ProductCategory>>;

export function GetProducts():Promise<Array<database.Product>>;

export function GetQRCodeInfo(arg1:string):Promise<Record<string, any>>;

export function GetSalesCategories():Promise<Array<database.SalesCategory>>;

export function GetTaxRates():Promise<Array<database.TaxRate>>;

export function GetUnitsOfMeasurement():Promise<Array<database.UnitOfMeasurement>>;

export function Greet(arg1:string):Promise<string>;

export function OpenPDFInViewer(arg1:string):Promise<void>;

export function RegenerateInvoiceQRCode(arg1:number):Promise<string>;

export function ShowError(arg1:string,arg2:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;

export function ShowSaveDialog(arg1:string):Promise<string>;

export function UpdateCompany(arg1:database.Company):Promise<void>;

export function UpdateCustomer(arg1:database.Customer):Promise<void>;

export function UpdateDefaultProductSettings(arg1:database.DefaultProductSettings):Promise<void>;

export function UpdatePayment(arg1:database.Payment):Promise<void>;

export function UpdatePaymentType(arg1:database.PaymentType):Promise<void>;

export function UpdateProduct(arg1:database.Product):Promise<void>;

export function UpdateSalesCategory(arg1:database.SalesCategory):Promise<void>;

export function UpdateTaxRate(arg1:database.TaxRate):Promise<void>;

export function UpdateUnitOfMeasurement(arg1:database.UnitOfMeasurement):Promise<void>;

export function ValidateZATCAQRCode(arg1:string):Promise<void>;
