// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCustomer(arg1:main.Customer):Promise<void>;

export function CreateInvoice(arg1:main.Invoice):Promise<void>;

export function CreateItemCategory(arg1:main.ItemCategory):Promise<void>;

export function CreateSaleItem(arg1:main.SaleItem):Promise<void>;

export function DeleteCustomer(arg1:number):Promise<void>;

export function GenerateInvoicePDF(arg1:number):Promise<string>;

export function GenerateSampleQRCode():Promise<string>;

export function GetCompany():Promise<main.Company>;

export function GetCustomerByID(arg1:number):Promise<main.Customer>;

export function GetCustomers():Promise<Array<main.Customer>>;

export function GetInvoiceByID(arg1:number):Promise<main.Invoice>;

export function GetInvoices():Promise<Array<main.Invoice>>;

export function GetItemCategories():Promise<Array<main.ItemCategory>>;

export function GetQRCodeInfo(arg1:string):Promise<Record<string, any>>;

export function GetSaleItems():Promise<Array<main.SaleItem>>;

export function Greet(arg1:string):Promise<string>;

export function OpenPDFInViewer(arg1:string):Promise<void>;

export function RegenerateInvoiceQRCode(arg1:number):Promise<string>;

export function ShowError(arg1:string,arg2:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;

export function ShowSaveDialog(arg1:string):Promise<string>;

export function UpdateCompany(arg1:main.Company):Promise<void>;

export function UpdateCustomer(arg1:main.Customer):Promise<void>;

export function ValidateZATCAQRCode(arg1:string):Promise<void>;
