// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCustomer(arg1) {
  return window['go']['main']['App']['CreateCustomer'](arg1);
}

export function CreateInvoice(arg1) {
  return window['go']['main']['App']['CreateInvoice'](arg1);
}

export function CreateItemCategory(arg1) {
  return window['go']['main']['App']['CreateItemCategory'](arg1);
}

export function CreateSaleItem(arg1) {
  return window['go']['main']['App']['CreateSaleItem'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['main']['App']['DeleteCustomer'](arg1);
}

export function GenerateInvoicePDF(arg1) {
  return window['go']['main']['App']['GenerateInvoicePDF'](arg1);
}

export function GetCompany() {
  return window['go']['main']['App']['GetCompany']();
}

export function GetCustomerByID(arg1) {
  return window['go']['main']['App']['GetCustomerByID'](arg1);
}

export function GetCustomers() {
  return window['go']['main']['App']['GetCustomers']();
}

export function GetInvoiceByID(arg1) {
  return window['go']['main']['App']['GetInvoiceByID'](arg1);
}

export function GetInvoices() {
  return window['go']['main']['App']['GetInvoices']();
}

export function GetItemCategories() {
  return window['go']['main']['App']['GetItemCategories']();
}

export function GetQRCodeInfo(arg1) {
  return window['go']['main']['App']['GetQRCodeInfo'](arg1);
}

export function GetSaleItems() {
  return window['go']['main']['App']['GetSaleItems']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenPDFInViewer(arg1) {
  return window['go']['main']['App']['OpenPDFInViewer'](arg1);
}

export function RegenerateInvoiceQRCode(arg1) {
  return window['go']['main']['App']['RegenerateInvoiceQRCode'](arg1);
}

export function ShowError(arg1, arg2) {
  return window['go']['main']['App']['ShowError'](arg1, arg2);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function ShowSaveDialog(arg1) {
  return window['go']['main']['App']['ShowSaveDialog'](arg1);
}

export function UpdateCompany(arg1) {
  return window['go']['main']['App']['UpdateCompany'](arg1);
}

export function UpdateCustomer(arg1) {
  return window['go']['main']['App']['UpdateCustomer'](arg1);
}

export function ValidateZATCAQRCode(arg1) {
  return window['go']['main']['App']['ValidateZATCAQRCode'](arg1);
}
