// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCustomer(arg1) {
  return window['go']['main']['App']['CreateCustomer'](arg1);
}

export function CreateInvoice(arg1) {
  return window['go']['main']['App']['CreateInvoice'](arg1);
}

export function CreatePayment(arg1) {
  return window['go']['main']['App']['CreatePayment'](arg1);
}

export function CreatePaymentType(arg1) {
  return window['go']['main']['App']['CreatePaymentType'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['main']['App']['CreateProduct'](arg1);
}

export function CreateProductCategory(arg1) {
  return window['go']['main']['App']['CreateProductCategory'](arg1);
}

export function CreateSalesCategory(arg1) {
  return window['go']['main']['App']['CreateSalesCategory'](arg1);
}

export function CreateSampleData() {
  return window['go']['main']['App']['CreateSampleData']();
}

export function CreateTaxRate(arg1) {
  return window['go']['main']['App']['CreateTaxRate'](arg1);
}

export function CreateUnitOfMeasurement(arg1) {
  return window['go']['main']['App']['CreateUnitOfMeasurement'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['main']['App']['DeleteCustomer'](arg1);
}

export function DeletePayment(arg1) {
  return window['go']['main']['App']['DeletePayment'](arg1);
}

export function DeletePaymentType(arg1) {
  return window['go']['main']['App']['DeletePaymentType'](arg1);
}

export function DeleteSalesCategory(arg1) {
  return window['go']['main']['App']['DeleteSalesCategory'](arg1);
}

export function DeleteTaxRate(arg1) {
  return window['go']['main']['App']['DeleteTaxRate'](arg1);
}

export function DeleteUnitOfMeasurement(arg1) {
  return window['go']['main']['App']['DeleteUnitOfMeasurement'](arg1);
}

export function DownloadInvoicePDF(arg1) {
  return window['go']['main']['App']['DownloadInvoicePDF'](arg1);
}

export function GenerateInvoiceHTML(arg1) {
  return window['go']['main']['App']['GenerateInvoiceHTML'](arg1);
}

export function GenerateInvoicePDF(arg1) {
  return window['go']['main']['App']['GenerateInvoicePDF'](arg1);
}

export function GenerateSampleQRCode() {
  return window['go']['main']['App']['GenerateSampleQRCode']();
}

export function GetCompany() {
  return window['go']['main']['App']['GetCompany']();
}

export function GetCustomerByID(arg1) {
  return window['go']['main']['App']['GetCustomerByID'](arg1);
}

export function GetCustomers() {
  return window['go']['main']['App']['GetCustomers']();
}

export function GetDefaultProductSettings() {
  return window['go']['main']['App']['GetDefaultProductSettings']();
}

export function GetInvoiceByID(arg1) {
  return window['go']['main']['App']['GetInvoiceByID'](arg1);
}

export function GetInvoices() {
  return window['go']['main']['App']['GetInvoices']();
}

export function GetPaymentByID(arg1) {
  return window['go']['main']['App']['GetPaymentByID'](arg1);
}

export function GetPaymentTypes() {
  return window['go']['main']['App']['GetPaymentTypes']();
}

export function GetPayments() {
  return window['go']['main']['App']['GetPayments']();
}

export function GetPaymentsByInvoiceID(arg1) {
  return window['go']['main']['App']['GetPaymentsByInvoiceID'](arg1);
}

export function GetProductCategories() {
  return window['go']['main']['App']['GetProductCategories']();
}

export function GetProducts() {
  return window['go']['main']['App']['GetProducts']();
}

export function GetQRCodeInfo(arg1) {
  return window['go']['main']['App']['GetQRCodeInfo'](arg1);
}

export function GetSalesCategories() {
  return window['go']['main']['App']['GetSalesCategories']();
}

export function GetTaxRates() {
  return window['go']['main']['App']['GetTaxRates']();
}

export function GetUnitsOfMeasurement() {
  return window['go']['main']['App']['GetUnitsOfMeasurement']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenPDFInViewer(arg1) {
  return window['go']['main']['App']['OpenPDFInViewer'](arg1);
}

export function PrintInvoiceHTML(arg1) {
  return window['go']['main']['App']['PrintInvoiceHTML'](arg1);
}

export function RegenerateInvoiceQRCode(arg1) {
  return window['go']['main']['App']['RegenerateInvoiceQRCode'](arg1);
}

export function SaveInvoiceHTML(arg1) {
  return window['go']['main']['App']['SaveInvoiceHTML'](arg1);
}

export function ShowError(arg1, arg2) {
  return window['go']['main']['App']['ShowError'](arg1, arg2);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function ShowSaveDialog(arg1) {
  return window['go']['main']['App']['ShowSaveDialog'](arg1);
}

export function UpdateCompany(arg1) {
  return window['go']['main']['App']['UpdateCompany'](arg1);
}

export function UpdateCustomer(arg1) {
  return window['go']['main']['App']['UpdateCustomer'](arg1);
}

export function UpdateDefaultProductSettings(arg1) {
  return window['go']['main']['App']['UpdateDefaultProductSettings'](arg1);
}

export function UpdatePayment(arg1) {
  return window['go']['main']['App']['UpdatePayment'](arg1);
}

export function UpdatePaymentType(arg1) {
  return window['go']['main']['App']['UpdatePaymentType'](arg1);
}

export function UpdateProduct(arg1) {
  return window['go']['main']['App']['UpdateProduct'](arg1);
}

export function UpdateSalesCategory(arg1) {
  return window['go']['main']['App']['UpdateSalesCategory'](arg1);
}

export function UpdateTaxRate(arg1) {
  return window['go']['main']['App']['UpdateTaxRate'](arg1);
}

export function UpdateUnitOfMeasurement(arg1) {
  return window['go']['main']['App']['UpdateUnitOfMeasurement'](arg1);
}

export function ValidateZATCAQRCode(arg1) {
  return window['go']['main']['App']['ValidateZATCAQRCode'](arg1);
}

export function ViewInvoiceHTML(arg1) {
  return window['go']['main']['App']['ViewInvoiceHTML'](arg1);
}

export function ViewInvoicePDF(arg1) {
  return window['go']['main']['App']['ViewInvoicePDF'](arg1);
}
